site_name: 'Test'
site_description: "Documentation for Customer Service"
repo_url: https://github.com/svkaizoku/github-tasks
nav:
  - Overview: 'index.md'
plugins:
  - techdocs-core
markdown_extensions:
  - markdown_inline_mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.9/mermaid.neutral.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.9/mermaid.min.js
  


