site_name: 'Test'
site_description: "Documentation for Customer Service"
repo_url: https://github.com/svkaizoku/github-tasks
nav:
  - Overview: 'index.md'
plugins:
  - techdocs-core
markdown_extensions:
  - markdown_inline_mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_mermaid_custom
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js  


