site_name: 'Test'
site_description: "Documentation for Customer Service"
repo_url: https://github.com/svkaizoku/github-tasks
nav:
  - Overview: 'index.md'
plugins:
  - techdocs-core
markdown_extensions:
  pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

