# This is a basic workflow that is manually triggered

name: Manual workflow new one

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      type_selected:
        required: true
        type: choice
        description: Wf for send
        options:
          - greet
          - bye
          - snyk

          # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  display_choice:
     runs-on: ubuntu-latest
     steps:
      # Runs a single command using the runners shell
      - name: Selected choice is
        run: echo "Hello ${{ inputs.type_selected }} . greet ${{ inputs.type_selected == 'greet' }} , bye  ${{ inputs.type_selected == 'bye' }}"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ inputs.type_selected == 'greet' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
  bye:
    runs-on: ubuntu-latest
    if: ${{ inputs.type_selected == 'bye' }}
    steps:
      - name: Send bye
        run: echo "Bye ${{ inputs.bye }}"
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    if: ${{ inputs.type_selected == 'snyk' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: 17
      - name: Setup cli
        uses: snyk/actions/setup@master
      - name: Run snyk
        working-directory: ./movie
        run: |
          set +e
          snyk test --severity-threshold=high --reachable --project-name=svkaizoku/movie
          exit_code=$?
          echo exit_code
          snyk monitor --reachable --project-name=svkaizoku/movie
          exit $exit_code
