name: Snyk Pipeline
on: push
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: 17
      - name: Setup cli
        uses: snyk/actions/setup@master
      - name: Run snyk
        working-directory: ./movie
        run: |
          set +e
          snyk test --severity-threshold=high --reachable --project-name=svkaizoku/movie
          exit_code=$?
          echo exit_code
          snyk monitor --reachable --project-name=svkaizoku/movie
          exit $exit_code
