name: Snyk Pipeline
on: push
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup cli
        uses: snyk/actions/setup@master
      - name: Run snyk
        working-directory: ./movie
        run: |
          set +e
          snyk test --severity-threshold=high --fail-on=all --reachable --project-name=movie
          exit_code=$?
          snyk monitor --reachable --project-name=movie
          exit $exit_code
