name: Snyk Pipeline
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup cli
        uses: snyk/actions/setup@master
      - name: Run snyk
        run: |
          set +e
          snyk test --severity-threshold=high --fail-on=all --reachable --project-name=github-tasks
          exit_code=$?
          snyk monitor --reachable --project-name=github-tasks
          exit $exit_code
